javascript: (function() {
    const body = document.querySelector('body');
    const highlights = [...document.querySelectorAll('#highlight')];
    const newHighlights = highlights.map(highlight => `${highlight.innerText}`).join('\n\n');
    const input = document.createElement('textarea');
    const close = document.createElement('button');
    input.value = newHighlights;
    input.style.position = 'absolute';
    input.style.left = 0;
    input.style.top = 0;
    input.style.width = '100%';
    input.style.height = '100%';
    input.style.backgroundColor = 'white';
    input.style.fontSize = '14px';
    input.style.paddingTop = '50px';
    input.classList.add('myClipboard');
    body.appendChild(input);
    const myClipboard = document.querySelector('.myClipboard');
    myClipboard.focus();
    myClipboard.select();
    close.innerText = 'Close';
    close.style.position = 'absolute';
    close.style.right = '10px';
    close.style.top = '10px';
    close.style.padding = '5px';
    close.style.border = 'none';
    close.style.zIndex = 10;
    close.style.backgroundColor = 'black';
    close.style.color = 'white';
    close.style.fontWeight = 'bold';
    close.style.fontSize = '16px';
    close.classList.add('closeClipboard');
    body.appendChild(close);
    const closeBtn = document.querySelector('.closeClipboard');
    closeBtn.addEventListener("click", function(e) {
        myClipboard.remove();
        closeBtn.remove();
    });
})();